# This job runs our automated buid process

name: Release

on:
  push:
    branches:
      - main  
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    
    permissions:
       id-token: write
       contents: read
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
          submodules: true 
          fetch-depth: 0 
          
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
          hugo-version: 'latest'
          extended: true

    - name: Build
      run: hugo --minify
        
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with: 
          name: tech-blog
          path: public/*

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
         audience: sts.amazonaws.com
         aws-region: eu-west-1
         role-to-assume: ${{ secrets.AWS_IAM_ROLE }}


    - name: Sync blog content to S3 bucket 
      run: |
         aws s3 sync ./public/ s3://${{ secrets.S3_SECRET }} --delete

    - name: create cloudfront invalidation to clear cache
      run: |
         aws cloudfront create-invalidation \
         --distribution-id ${{ secrets.AWS_CLOUDFRONT_SECRET }} \ --paths "/*"
